services:

  db:
    build: ./src/database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - .data/postgres:/var/lib/postgresql/data
    restart: always

  crawler:
    build: ./src/crawler
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - OLLAMA_HOST=http://ollama:11434
    restart: always
    depends_on:
      - db
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes:
      - .data/ollama:/root/.ollama
    restart: always
